name: flutterfolio
description: "A new Flutter Portfolio project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  responsive_builder: ^0.7.0
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.0.9
  flutter_feather_icons: ^2.0.0+1
  animated_text_kit: ^4.2.1
  visibility_detector: ^0.4.0+2
  flutter_bloc: ^8.1.5  
  layout: ^1.0.5
  freezed_annotation: ^2.4.1
  dartz: ^0.10.0
  get_it: ^7.2.0
  flutter_spinkit: ^5.0.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/projects/
    - assets/images/projects/flutterfolio/
    - assets/images/projects/petomate/
    - assets/images/projects/wallies/
    - assets/screenshots/

  fonts:
    - family: VisueltPro
      fonts:
        - asset: assets/fonts/visuelt/VisueltPro-Thin.ttf
          weight: 100
        - asset: assets/fonts/visuelt/VisueltPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/visuelt/VisueltPro-Light.ttf
          weight: 300
        - asset: assets/fonts/visuelt/VisueltPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/visuelt/VisueltPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/visuelt/VisueltPro-Black.ttf
          weight: 700
        - asset: assets/fonts/visuelt/VisueltPro-Bold.ttf
          weight: 800
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700